[main]
project_root_dir = 'michelle_classes'

[load]
prefixes = [ '1_', '2_', '3_', '4_', '5_', '6_', '7_', '8_', '9_', '10_', '11_' ]
train_data_dir = 'dataset'
output_data_dir = 'features_michelle_classes'

[load.fasta_labels]
baseplate = 'BPL'
HTJ = 'HTJ'
major_tail = 'MTL'
minor_tail = 'm_TL'
portal = 'PTL'
tail_fiber = 'TFR'
collar = 'CLR'
major_capsid = 'MCP'
minor_capsid = 'm_CP'
shaft = 'TSH'
others = 'OTH'

[load.class_number]
BPL = 1
BPU = 2
CTF = 3
HTJ = 4
HTC = 5
MCP = 6
MTL = 7
m_TL = 8
PTL = 9
TSH = 10
TSP = 11
OTH = 12

[train]
model_dir = 'models_michelle_classes/'

[train.models]
di_sc = true
di_sc_p = false
tri_sc = false
tri_sc_p = false
tetra_sc = false
tetra_sc_p = false
di = false
di_p = false
tri = false
tri_p = false
tetra_sc_tri_p = false
all = false

[test]
model = 'all'