[main]
project_root_dir = '.'

[load]
prefixes = [ '1_', '2_', '3_', '4_', '5_', '6_', '7_', '8_', '9_', '10_', '11_']
train_data_dir = 'dataset'
output_data_dir = 'features'

[load.fasta_labels]
major_capsid = 'MCP'
minor_capsid = 'm_CP'
baseplate = 'BPL'
major_tail = 'MTL'
minor_tail = 'm_TL'
portal = 'PTL'
tail_fiber = 'TFR'
shaft = 'TSH'
collar = 'CLR'
HTJ = 'HTJ'
others = 'OTH'

[load.class_number]
MCP = 1
m_CP = 2
BPL = 3
MTL = 4
m_TL = 5
PTL = 6
TFR = 7
TSH = 8
CLR = 9
HTJ = 10
OTH = 11

[train]
model_dir = 'models'

