[load]
prefixes = [ '1_', '2_', '3_', '4_', '5_', '6_', '7_', '8_', '9_', '10_', '11_']

fasta_labels.major_capsid = 'MCP'
fasta_labels.minor_capsid = 'm_CP'
fasta_labels.baseplate = 'BPL'
fasta_labels.major_tail = 'MTL'
fasta_labels.minor_tail = 'm_TL'
fasta_labels.portal = 'PTL'
fasta_labels.tail_fiber = 'TFR'
fasta_labels.shaft = 'TSH'
fasta_labels.collar = 'CLR'
fasta_labels.HTJ = 'HTJ'
fasta_labels.others = 'OTH'

train_data_dir = 'dataset'
output_data_dir = 'features'

class_number.MCP = 1
class_number.m_CP = 2
class_number.BPL = 3
class_number.MTL = 4
class_number.m_TL = 5
class_number.PTL = 6
class_number.TFR = 7
class_number.TSH = 8
class_number.CLR = 9
class_number.HTJ = 10
class_number.OTH = 11
