[load]
prefixes = [ '1_', '2_', '3_', '4_', '5_', '6_', '7_', '8_', '9_', '10_', '11_']
fasta_labels = {
    major_capsid.fasta = 'MCP',
    minor_capsid.fasta = 'm_CP',
    baseplate.fasta = 'BPL',
    major_tail.fasta = 'MTL',
    minor_tail.fasta = 'm_TL',
    portal.fasta = 'PTL',
    tail_fiber.fasta = 'TFR',
    shaft.fasta = 'TSH',
    collar.fasta = 'CLR',
    HTJ.fasta = 'HTJ',
    others.fasta = 'OTH'
 }
train_data_dir = 'dataset'
output_data_dir = 'features'
